export const defaultStatBlocks = {
  Default: {
    class: "Default",
    level: 1,
    HP: 10,
    AC: 10,
    abilities: {
      strength: 10,
      dexterity: 10,
      constitution: 10,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
    },
  },
  Fighter: {
    class: "Fighter",
    level: 1,
    HP: 12,
    AC: 16,
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 14,
      intelligence: 10,
      wisdom: 12,
      charisma: 8,
    },
  },
  Barbarian: {
    class: "Barbarian",
    level: 1,
    HP: 14,
    AC: 13,
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 14,
      intelligence: 10,
      wisdom: 12,
      charisma: 8,
    },
  },
  Ranger: {
    class: "Ranger",
    level: 1,
    HP: 11,
    AC: 14,
    abilities: {
      strength: 12,
      dexterity: 15,
      constitution: 13,
      intelligence: 10,
      wisdom: 14,
      charisma: 8,
    },
  },
  Rogue: {
    class: "Rogue",
    level: 1,
    HP: 10,
    AC: 14,
    abilities: {
      strength: 10,
      dexterity: 15,
      constitution: 14,
      intelligence: 13,
      wisdom: 12,
      charisma: 8,
    },
  },
  Priest: {
    class: "Priest",
    level: 1,
    HP: 10,
    AC: 18,
    abilities: {
      strength: 13,
      dexterity: 12,
      constitution: 14,
      intelligence: 10,
      wisdom: 15,
      charisma: 8,
    },
  },

  Paladin: {
    class: "Paladin",
    level: 1,
    HP: 11,
    AC: 18,
    abilities: {
      strength: 15,
      dexterity: 12,
      constitution: 13,
      intelligence: 8,
      wisdom: 10,
      charisma: 14,
    },
  },
};

